repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.4.4"
    hooks:
      - id: ruff
        args: ['--fix']

  - repo: https://github.com/psf/black
    rev: "24.4.2"
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.10.0"
    hooks:
    -   id: mypy
        additional_dependencies: [types-aiofiles==23.2.0.20240403]
